# Generated by Django 3.2 on 2021-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testbench', models.CharField(max_length=120)),
                ('code', models.TextField()),
            ],
        ),
    ]
